apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      volumes:
      - name: csci5409-pvc
        persistentVolumeClaim:
          claimName: csci5409-pvc
      containers:
      - name: container1
        image: gcr.io/csci5409-a-k8s/container1
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: csci5409-pvc 
          mountPath: /tirth_PV_dir
---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  selector:
    app: container1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer