apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      volumes:
      - name: csci5409-pvc
        persistentVolumeClaim:
          claimName: csci5409-pvc
      containers:
      - name: container2
        image: gcr.io/csci5409-a-k8s/container2
        ports:
        - containerPort: 4000
        volumeMounts:
        - name: csci5409-pvc
          mountPath: /tirth_PV_dir
